//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> ProductCreateTime { get; set; }
        public Nullable<System.DateTime> ProductModifiedTime { get; set; }
        public Nullable<bool> ProductIsActive { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
